### ISSUE TITLE
Querying the TNS: cannot convert float NaN to integer

### ISSUE THREAD

**Issue by 0xCoto** [davidgardenier/frbcat#12]
@davidgardenier - Any ideas what might be causing this error all of a sudden? Perhaps some new TNS entry contains data in an unusual format?
```py
Traceback (most recent call last):
  File "/home/runner/work/FRBSTATS/FRBSTATS/FRBSTATS/tns_compare.py", line 56, in <module>
    tns = TNS(path='/home/runner/', tns_name='my_user_name', tns_id='my_user_id')
  File "/usr/local/lib/python3.10/dist-packages/frbcat/tns.py", line 54, in __init__
    self.get_data()
  File "/usr/local/lib/python3.10/dist-packages/frbcat/tns.py", line 127, in get_data
    self.clean_df(df)
  File "/usr/local/lib/python3.10/dist-packages/frbcat/tns.py", line 305, in clean_df
    df = df.astype({'tns_id': int,
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/generic.py", line 6226, in astype
    res_col = col.astype(dtype=cdt, copy=copy, errors=errors)
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/generic.py", line 6240, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/internals/managers.py", line 450, in astype
    return self.apply("astype", dtype=dtype, copy=copy, errors=errors)
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/internals/managers.py", line 352, in apply
    applied = getattr(b, f)(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/internals/blocks.py", line 526, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/dtypes/astype.py", line 299, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/dtypes/astype.py", line 230, in astype_array
    values = astype_nansafe(values, dtype, copy=copy)
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/dtypes/astype.py", line 170, in astype_nansafe
    return arr.astype(dtype, copy=True)
ValueError: cannot convert float NaN to integer
```
Full code: https://github.com/HeRTA/FRBSTATS/blob/main/tns_compare.py

**Comment by 0xCoto** [comment]
@loostrum It did work, yeah. I don't think the problem is related to the credentials (never had an issue using these example values).

**Comment by 0xCoto** [comment]
@andrewzwaniga Looping you in, in case you're aware of any recent infrastructure changes of some sort from the TNS's point of view.

**Comment by loostrum** [comment]
Thanks for the update. Even if it did work, I'd still advise to use proper TNS credentials. They may be surprised if they get many requests from a user called my_user_name ;)
For the issue: it seems that some columns previously only containing integer values can now contain NaNs as well. I've pushed a fix to replace those by -1 before the conversion to int. Let me know if that solves your problem.

**Comment by 0xCoto** [comment]
Thanks, that seems to have fixed it!
