### ISSUE TITLE
TNS: 'host_redshift' not found in columns

### ISSUE THREAD

**Issue by 0xCoto** [davidgardenier/frbcat#14]
@loostrum - Any idea why that is?
```py
Traceback (most recent call last):
  File "/home/runner/work/FRBSTATS/FRBSTATS/FRBSTATS/tns_compare.py", line 56, in <module>
    tns = TNS(path='/home/runner/', tns_name='my_user_name', tns_id='my_user_id')
  File "/usr/local/lib/python3.10/dist-packages/frbcat/tns.py", line 54, in __init__
    self.get_data()
  File "/usr/local/lib/python3.10/dist-packages/frbcat/tns.py", line 127, in get_data
    self.clean_df(df)
  File "/usr/local/lib/python3.10/dist-packages/frbcat/tns.py", line 308, in clean_df
    df = df.astype({'tns_id': int,
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/generic.py", line 6212, in astype
    raise KeyError(
KeyError: "Only a column name can be used for the key in a dtype mappings argument. 'host_redshift' not found in columns."
```
Not sure if something suddenly changed in the TNS (hass been working fine so far).

Thanks!

**Comment by 0xCoto** [comment]
@davidgardenier @fjankowsk @andrewzwaniga looping you guys in, in case you happen to know if something might have changed with the TNS recently.

**Comment by fjankowsk** [comment]
Hi,

I ran into this issue too recently. Have you or anyone else found a fix for it in the meantime? It would be nice to get this fixed.

Cheers.
Fabian

**Comment by davidgardenier** [comment]
@loostrum You're probs best placed to look into this, but see how it fits in your schedule.
